feat: RecoveryManager role on GovernanceRouter
celo-org/optics-monorepo pull request #353
Opened 2021-05-20 12:16 UTC by anna-carroll

closes #299

2021-05-26 15:35 UTC, ltchang2019 commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        uint256 _recoveryActiveAt = recoveryActiveAt;
nit: Is this load into `_recoveryActiveAt` necessary?

2021-05-26 15:35 UTC, ltchang2019 commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +
Is this overflow-safe? Looks like we condition on `recoveryActiveAt` and `recoveryTimelock` a few times so just wanted to check

2021-05-26 15:53 UTC, ErinHales reviewed
nice! 😊

2021-05-26 15:53 UTC, ErinHales commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        return _recoveryInitiated && _recoveryTimelockExpired;
_recoveryTimelockExpired is actually checking if it has _not_ expired.  Would rename or change to:
```
bool _recoveryTimelockExpired = _recoveryActiveAt > block.number;
return _recoveryInitiated && !_recoveryTimelockExpired;
```

2021-05-26 15:53 UTC, ErinHales commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +    uint256 public recoveryActiveAt; // block number when recovery timelock expires; 0 if timelock has not been initiated
consider renaming, sounds like recovery starts at that block.  `recoveryExpiresAt`?

2021-06-18 17:27 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        uint256 _recoveryActiveAt = recoveryActiveAt;
it's really just to save the 800 gas of an extra SLOAD. since this function will be called in a modifier that will be added to nearly every external function

2021-06-18 17:29 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +
🤔 it shouldn't overflow given the real-world expected values of these vars...

2021-06-18 19:15 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +    uint256 public recoveryActiveAt; // block number when recovery timelock expires; 0 if timelock has not been initiated
`recovery` is the state in which the RecoveryManager is able to act in place of the governor; the `recovery` **timelock** expires at this block, while `recovery` itself is active at this block

2021-06-18 19:19 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        uint256 _recoveryActiveAt = recoveryActiveAt;
so, no, it's not necessary - it's a very small optimization

2021-06-18 21:39 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        return _recoveryInitiated && _recoveryTimelockExpired;
heck, yeah, great catch https://github.com/celo-org/optics-monorepo/pull/353/commits/a5ba7acb4bc86325a3b56f5e71e6de99e54dae38

2021-06-18 21:39 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +    uint256 public recoveryActiveAt; // block number when recovery timelock expires; 0 if timelock has not been initiated
renamed for a bit more clarity / consistency hopefully? https://github.com/celo-org/optics-monorepo/pull/353/commits/a5ba7acb4bc86325a3b56f5e71e6de99e54dae38

2021-06-18 21:52 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +    uint256 public recoveryActiveAt; // block number when recovery timelock expires; 0 if timelock has not been initiated
recovery timelock expired = recovery is active

2021-06-18 22:01 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        return _recoveryInitiated && _recoveryTimelockExpired;
hmm i see where the confusion is arising here. the name `recoveryTimelockExpired` is the same as the name `recoveryActive` - but perhaps the latter is more clear. 

let's say `recoveryTimelock` is 25 blocks, and the `recoveryManager` calls `initiateRecovery` at `block.number` 50. this means that `recoveryActiveAt` = 75 (the current block 50, plus 25 block timelock)

the 25-block recovery timelock expires at block 75. recovery is active at block 75. for any block that is greater than or equal to 75, recovery is active.

2021-06-18 22:05 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        return _recoveryInitiated && _recoveryTimelockExpired;
i renamed to `recoveryActive` to make this hopefully more clear?

2021-06-21 20:21 UTC, prestwich commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +    uint256 public recoveryActiveAt; // block number when recovery timelock expires; 0 if timelock has not been initiated
why did we choose to do a blocknumber instead of a timestamp?

2021-06-21 20:23 UTC, prestwich commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +    function setRouterLocal(uint32 _domain, bytes32 _router)
could be `enrollRouter` ?

2021-06-21 20:25 UTC, prestwich commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +
if you leave it as is, document that setting `recoveryTimelock` near u256 max has the opposite of intended behavior

2021-06-21 20:26 UTC, prestwich commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        uint256 _recoveryActiveAt = recoveryActiveAt;
the savings from doing this went down in eip2929, but are still important

2021-06-21 20:31 UTC, prestwich commented on solidity/optics-core/js/types.js
> + *      recoveryManager: address,  // NOTE: this may change if we add a multisig to the deploy setup
need to add these to the TS deploy process

2021-06-21 20:31 UTC, prestwich requested changes
see comments

2021-06-22 17:59 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +
switched to `SafeMath` : https://github.com/celo-org/optics-monorepo/pull/353/commits/d14e978939307ac81f261f2d88cf2b89d50ae0c0

2021-06-22 18:00 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +    uint256 public recoveryActiveAt; // block number when recovery timelock expires; 0 if timelock has not been initiated
switched https://github.com/celo-org/optics-monorepo/pull/353/commits/d14e978939307ac81f261f2d88cf2b89d50ae0c0

2021-06-22 18:01 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +    function setRouterLocal(uint32 _domain, bytes32 _router)
this function is used to add routers (enroll), remove routers (un-enroll), and change router addresses

2021-06-22 19:19 UTC, anna-carroll commented on solidity/optics-core/js/types.js
> + *      recoveryManager: address,  // NOTE: this may change if we add a multisig to the deploy setup
https://github.com/celo-org/optics-monorepo/pull/353/commits/1886f01a7560ece708985ca15b113b4e3ad59b8d

I can send you the updated `tmp.ts` for this and `test_deploy.env`

2021-06-22 20:08 UTC, prestwich commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        if (inRecovery()) {
nit: whichever check is more likely to pass should be first. In this case, the governor check

2021-06-22 20:11 UTC, prestwich requested changes
1 nit

2021-06-22 20:15 UTC, anna-carroll commented on solidity/optics-core/contracts/governance/GovernanceRouter.sol
> +        if (inRecovery()) {
https://github.com/celo-org/optics-monorepo/pull/353/commits/42c01a074bed74d849940cca361bbdc7d5f1dd02

2021-06-22 20:16 UTC, prestwich approved these changes

2021-06-22 20:18 UTC, merged