feature: add optics-xapps typechain gen
celo-org/optics-monorepo pull request #389
Opened 2021-06-10 18:42 UTC by YoduYodu

2021-06-10 19:21 UTC, prestwich requested changes

2021-06-10 19:21 UTC, prestwich commented on solidity/optics-xapps/hardhat.config.js
> +    outDir: '../../typescript/src/typechain',
I think this will overwrite the core contracts. instead, provide a separate directory for them

2021-06-10 20:03 UTC, YoduYodu commented on solidity/optics-xapps/hardhat.config.js
> +    outDir: '../../typescript/src/typechain',
I thought about that as well. So I've gone ahead and reorged it as follows
- typechain
    - optics-core
    - optics-xapps
    - [more contracts]

2021-06-10 20:34 UTC, ErinHales commented
You'll need to update the imports for the files you moved from '/typechain' to '/typechain/optics-xapps'.

2021-06-10 20:38 UTC, ErinHales commented
And, as we discussed, next step will be to add the typechain gen to the 'npm run compile' script and the pre-commit script

2021-06-11 02:10 UTC, prestwich commented
@YoduYodu it looks like you ran into the `git v2.24` bug and it deleted all files in the repo. you'll need to update your git version `brew install git` and then reload your terminal. you'll also want to check out the previous commit `git checkout main~1` and then redo whatever work was lost

@ErinHales any idea why the precommit script didn't stop him from using git v2.24?

2021-06-11 03:28 UTC, ErinHales commented
Oh no 😬 I will look into it

2021-06-11 17:36 UTC, ErinHales approved these changes
Looks good!

2021-06-11 17:42 UTC, merged