chore: add typechain generation to standard pre-commit script
celo-org/optics-monorepo pull request #392
Opened 2021-06-11 22:42 UTC by YoduYodu

closes #374

2021-06-13 16:26 UTC, prestwich requested changes

2021-06-13 16:26 UTC, prestwich commented on pre-commit.sh
> +    npx hardhat typechain
Add a check at the beginning to see if npx is installed

2021-06-13 19:19 UTC, prestwich requested changes

2021-06-13 19:19 UTC, prestwich commented on pre-commit.sh
>      git add .
this `git add` will not add the typechain or abis anymore. this is a bug introduced by moving things in the repo.

change to 
```
cd ../..
git add rust/optics-ethereum/abis
git add typescript/src/typechain
```

2021-06-13 19:19 UTC, prestwich commented on pre-commit.sh
>      git add .
same here. change to 

```
cd ../..
git add typescript/src/typechain
```

2021-06-13 20:47 UTC, ErinHales commented on pre-commit.sh
>      git add .
oops, good catch

2021-06-13 20:52 UTC, ErinHales commented on pre-commit.sh
> +    npx hardhat typechain
I think it would make sense to add this command to the compile script

2021-06-14 18:01 UTC, YoduYodu commented on pre-commit.sh
>  fi
Regarding comments, does it make sense to just say "compile" rather than "compile, update abis, typechain...", let the script document itself?

2021-06-14 18:07 UTC, ErinHales commented on pre-commit.sh
> +    git add typescript/src/typechain
This won't catch files that were modified by the linter.  Should we just `git add .` here? @prestwich

2021-06-14 19:07 UTC, prestwich commented on pre-commit.sh
> +    git add typescript/src/typechain
I think doing `git add .` would result in accidentally committing a bunch of files. instead can we explicitly add specific directories? in this case `solidity/optics-core/contracts` and `solidity/optics-core/libs` and `solidity/optics-core/interfaces`

2021-06-14 19:07 UTC, prestwich commented on solidity/optics-core/package.json
> +    "compile": "hardhat compile && npm run prettier && ./scripts/update_abis.sh && npx hardhat typechain",
no need for the npx here. the scripts already run in the node context

2021-06-14 19:07 UTC, prestwich commented on pre-commit.sh
>  fi
fine either way

2021-06-14 19:08 UTC, prestwich commented on solidity/optics-xapps/package.json
> +    "compile": "hardhat compile && npm run prettier && npx hardhat typechain",
ditto

2021-06-14 20:42 UTC, ErinHales commented on pre-commit.sh
> +    git add solidity/optics-xapps/libs
There isn't a libs folder in `optics-xapps` (:

2021-06-14 20:53 UTC, ErinHales approved these changes

2021-06-15 17:14 UTC, prestwich submitted a review, later dismissed
LGTM

2021-06-15 18:01 UTC, ErinHales approved these changes

2021-06-15 18:02 UTC, merged