test: setup for ts tests
celo-org/optics-monorepo pull request #395
Opened 2021-06-14 19:02 UTC by ErinHales

- migrate HardhatRuntimeEnvironment
 - add deploy for test contracts
 - test Common

2021-06-14 19:11 UTC, prestwich requested changes
okay, some good work here. I'd like to see us split up the tests and the dev deploys to a new typescript package. `typescript/optics-deploy` and `typescript/optics-test`

2021-06-14 19:33 UTC, ErinHales commented
> okay, some good work here. I'd like to see us split up the tests and the dev deploys to a new typescript package. `typescript/optics-deploy` and `typescript/optics-test`

Yep, that definitely makes sense.  I refactored the typescript directory a bit.  I didn't rename the `test` directory to `optics-test` though, because hardhat is stubborn

2021-06-14 19:38 UTC, prestwich commented
do you think it makes sense to have these be entirely separate packages? each with a package.json?

Then only the optics-test package would need hardhat

2021-06-14 19:46 UTC, ErinHales commented
> do you think it makes sense to have these be entirely separate packages? each with a package.json?
> 
> Then only the optics-test package would need hardhat

Possibly? Do you think we'd want to make optics-deploy into an npm package?

2021-06-15 00:11 UTC, YoduYodu commented on typescript/test/lib/index.ts
> +>>>>>>> Stashed changes
☝️

2021-06-16 18:29 UTC, ErinHales commented
TODO:Install packages in `typescript/typechain`

2021-06-16 19:04 UTC, ErinHales commented
Closing in favor of #400

2021-06-16 19:04 UTC, closed without merging