WIP: Erinhales/home tests
celo-org/optics-monorepo pull request #401
Opened 2021-06-16 19:21 UTC by ErinHales

2021-06-29 23:38 UTC, prestwich requested changes

2021-06-29 23:38 UTC, prestwich commented on typescript/optics-tests/test/home.test.ts
> +  it('Fails on valid double update proof', async () => {
leave a blank line between the tests

2021-06-30 15:40 UTC, prestwich commented on typescript/optics-tests/test/home.test.ts
> +const UpdaterManager = require('../../../solidity/optics-core/artifacts/contracts/UpdaterManager.sol/UpdaterManager.json');
can we change these to not be requires so we're not mixing syntax. you can import json in TS by adding ` "resolveJsonModule": true,` to the compiler options in the `.tsconfig`

2021-06-30 16:41 UTC, prestwich approved these changes

2021-06-30 19:58 UTC, prestwich reviewed
looking good, still need to change requires to imports

2021-06-30 20:01 UTC, ErinHales commented
> looking good, still need to change requires to imports

I thought I got all of them...  Looks like I missed hardhat.config.ts, but I don't think there are any others?

2021-06-30 20:02 UTC, merged