Remove return values from `handle`
celo-org/optics-monorepo pull request #404
Opened 2021-06-17 15:55 UTC by anna-carroll

Closes #403

2021-06-17 15:59 UTC, prestwich requested changes

2021-06-17 15:59 UTC, prestwich commented on solidity/optics-core/contracts/Replica.sol
> +        } catch (bytes memory _err) {
I think this has the same problem. if the MessageRecipient reverts with data that can't be abi decoded as a `bytes`, it will cause our contract to revert

2021-06-17 16:01 UTC, prestwich commented on solidity/optics-core/contracts/Replica.sol
> +        } catch (bytes memory _err) {
for an example

```
assembly {
    revert(0,0)    
}
```

this would revert and the returndata would be set to the empty byte array`[]`, which would then fail when solidity attempts to decode as `bytes memory _err`

2021-06-17 23:45 UTC, anna-carroll commented on solidity/optics-core/contracts/Replica.sol
> +        } catch (bytes memory _err) {
Hmm interesting, so this actually worked in the test that I wrote: https://github.com/celo-org/optics-monorepo/pull/404/commits/3dc4dbd01f96876f3d1ded292670b2c5b345ab06

2021-06-17 23:51 UTC, anna-carroll commented on solidity/optics-core/contracts/Replica.sol
> +        } catch (bytes memory _err) {
ah yeah, so i got my info about try/catch [here](https://blog.ethereum.org/2020/01/29/solidity-0.6-try-catch/) and it specifically says 

> The advantage of the second method is that it is also executed if ABI decoding the error string fails or if no reason was provided.

which i checked before writing this and then promptly forgot again

2021-06-18 15:31 UTC, prestwich requested changes

2021-06-18 15:31 UTC, prestwich commented on solidity/optics-core/test/Replica.test.js
> +  it('Processes a message that reverts during handle', async () => {
can we add some similar tests for:
```
assembly {
    return(0,0)
}

assembly {
    mstore(0, 0xabcdefg)
    return(0,32)
}

assembly {
    mstore(0, 0xabcdefg)
    revert(0, 32)
}
```

2021-06-18 17:12 UTC, anna-carroll commented on solidity/optics-core/test/Replica.test.js
> +  it('Processes a message that reverts during handle', async () => {
🤠 https://github.com/celo-org/optics-monorepo/pull/404/commits/c6d29c6974a1eaafab7ea1eabd39a8675be415bf

2021-06-18 17:12 UTC, anna-carroll commented on solidity/optics-core/test/Replica.test.js
> +  it('Processes a message that reverts during handle', async () => {
I removed the expectation that `success` would be `false`, as two of these "Bad" recipients don't actually revert

2021-06-21 20:53 UTC, prestwich approved these changes
👍

2021-06-21 20:56 UTC, merged