Verify contract code after deploy script
celo-org/optics-monorepo pull request #448
Opened 2021-07-02 16:02 UTC by anna-carroll

2021-07-02 16:46 UTC, prestwich commented on solidity/optics-core/hardhat.config.js
> +    apiKey: "[INSERT KEY]"
load from env var

2021-07-05 19:05 UTC, prestwich commented
is this PR for informational purposes, or is it something we expect to merge eventually?

2021-07-06 13:28 UTC, anna-carroll commented
> is this PR for informational purposes, or is it something we expect to merge eventually?

it was originally informational, so I could push something we would both look at, but I have co-opted the branch / PR for the actual feature

2021-07-06 13:28 UTC, anna-carroll commented
**TODO:** 
- [ ] load etherscan API key from process.env 
- [ ] switch networks automatically using hardhat-ethers rather than .env variables 
- [ ] create an npm script to first run the deploy script then run the verify script 
- [ ] test the end-to-end flow

2021-07-07 16:34 UTC, anna-carroll commented on solidity/optics-core/hardhat.config.js
> +    apiKey: "[INSERT KEY]"
https://github.com/celo-org/optics-monorepo/pull/448/commits/e02e0c71eb052cd3910b14214819799275902d1b

2021-07-07 17:24 UTC, prestwich requested changes

2021-07-07 17:24 UTC, prestwich commented on solidity/optics-core/package.json
> +    "test": "npm run compile && hardhat --network hardhat test",
still needed?

2021-07-07 17:24 UTC, prestwich commented on typescript/src/proxyUtils.ts
> +  name: string,
you can get the class name using `implementation.constructor.name` instead of passing it as a string

2021-07-07 17:24 UTC, prestwich commented on typescript/src/proxyUtils.ts
> +    name: string,
you can get the class name using `prev.implementation.constructor.name` instead of passing it as a string

2021-07-07 17:27 UTC, prestwich commented on typescript/src/proxyUtils.ts
> +    name: string,
this may not actually work correctly 🤔

2021-07-07 17:29 UTC, anna-carroll commented on typescript/src/proxyUtils.ts
> +    name: string,
https://github.com/celo-org/optics-monorepo/pull/448/commits/2f7343bf7058c5d05ee8990a183edfc5e3893509

2021-07-07 17:30 UTC, anna-carroll commented on typescript/src/proxyUtils.ts
> +  name: string,
https://github.com/celo-org/optics-monorepo/pull/448/commits/2f7343bf7058c5d05ee8990a183edfc5e3893509

2021-07-07 17:30 UTC, anna-carroll commented on solidity/optics-core/package.json
> +    "test": "npm run compile && hardhat --network hardhat test",
https://github.com/celo-org/optics-monorepo/pull/448/commits/923f12a22b0f02e964d73612b92df200850f5744

2021-07-08 16:12 UTC, prestwich commented
can you also reset to main and remove the committed files that aren't relevant?


```
git checkout main
git pull
git checkout anna/verify
git reset main --soft
git status

# add only relevant files
git add {specific thing}

git commit --no-verify
git push
```

2021-07-08 16:57 UTC, prestwich commented on solidity/optics-core/env.js
> +const envy = require('envy');
do we still need this?

2021-07-08 17:53 UTC, anna-carroll commented on solidity/optics-core/env.js
> +const envy = require('envy');
https://github.com/celo-org/optics-monorepo/pull/448/commits/75ca26f76a4693b3dea1c8d76928b8f430d85a82

2021-07-08 17:54 UTC, anna-carroll commented
> can you also reset to main and remove the committed files that aren't relevant?

yep removed 🙂 there is still the deploy output and the new typescript, though 👍

2021-07-08 19:45 UTC, prestwich commented on typescript/package.json
> +    "deploy": "npx ts-node ./scripts/deploy.ts && cd ../solidity/optics-core && npm run verify"
relies on a non-existant file

2021-07-08 19:48 UTC, prestwich requested changes
can't have an npm script rely on an uncommitted file. everything else is looking good. I ran prettier on all your stuff

2021-07-08 19:55 UTC, prestwich approved these changes

2021-07-08 20:25 UTC, merged