Add BridgeRouter to deploy script
celo-org/optics-monorepo pull request #478
Opened 2021-07-08 16:11 UTC by anna-carroll

2021-07-08 16:18 UTC, prestwich commented
conceptual question: 
is the bridge a core xapp that should always be deployed? if so, how should it be integrated with governance?

2021-07-08 16:52 UTC, prestwich commented
need to enroll the bridge routers with eachother

2021-07-08 17:26 UTC, anna-carroll commented
> **Discussion**: should we also add a separate deploy process for the `BridgeRouter` only, so that we don't have to re-deploy the whole suite as we iterate on the `BridgeRouter`?

**Conclusion**: we want a separate deploy process for the `BridgeRouter`. the process will intake the timestamp of the latest core system deploy, pull the networks included in that deploy from the config folder, deploy the `BridgeRouter` for each chain, enroll the peer `BridgeRouters` with each other, then pass control of the `BridgeRouter` to governance. the deploy script will output the Bridge deploy information to a `bridge` subdirectory of the existing deploy config folder

2021-07-09 15:22 UTC, anna-carroll commented
⚠️ **Not ready for review yet** ⚠️ 

**TODO:** 
- [ ] debug `npm run deploy-core`
- [ ] add domain for BridgeRouter enroll - options: (1) parse from config (2) query on-chain (3) add to Chain type
- [ ] output bridge deploy to subfolder of optics core deploy
- [ ] switch envy for dotenv?
- [ ] add typescript/.env to README

2021-07-13 17:47 UTC, anna-carroll commented
**Deprioritized**
- _xApp contract code is not in core directory, so can't verify those contracts from the same core script_  
   - possible fixes: 
      - migrate verify to typescript directory & run verify script there
      - duplicate verify script within optics-xapps directory (bad)
      - move optics-xapps contracts to optics-core (bad)
   - best solution = use typescript script once we migrate to typescript
   - don't want to block this PR on this issue 
   - moved feature to separate issue (#487) and PR (#488); removed code from this PR: https://github.com/celo-org/optics-monorepo/pull/478/commits/503383426c509f2919580b5f952b662ee47825d2

2021-07-13 17:55 UTC, ErinHales commented
> **Deprioritized**
> 
> * _xApp contract artifacts are in optics-xapps directory, but script is running using ethers in optics-core directory, so verifying doesn't work yet_
>   
>   * possible fixes:
>     
>     * migrate verify to typescript directory & run verify script there
>     * duplicate verify script within optics-xapps directory (bad)
>     * move optics-xapps contracts to optics-core (bad)
>   * best solution = use typescript script once we migrate to typescript
>   * don't want to block this PR on this issue
>   * moved feature to separate issue ([feature: verify bridge deploy script #487](https://github.com/celo-org/optics-monorepo/issues/487)) and PR ([Verify latest bridge deploy #488](https://github.com/celo-org/optics-monorepo/pull/488)); removed code from this PR: [5033834](https://github.com/celo-org/optics-monorepo/commit/503383426c509f2919580b5f952b662ee47825d2)

ok, yes, was going to comment on this.  I want to move the verification over to typescript.  Do you think it would be easier to merge ts migration or this first?

2021-07-16 15:21 UTC, anna-carroll commented on typescript/optics-deploy/src/bridge.ts
> +  static freshFromConfig(config: ChainConfig, coreDeployPath: string): BridgeDeploy {
NOTE: I am working on refactoring this to have a class BaseDeploy that both Deploy and BridgeDeploy both extend, I am just trying to work out the typescript stuff between `Chain` and `OpticsChain`

2021-07-16 17:09 UTC, prestwich requested changes

2021-07-16 17:09 UTC, prestwich commented on typescript/optics-deploy/src/bridge.ts
> +  static freshFromConfig(config: ChainConfig, coreDeployPath: string): BridgeDeploy {
ah so here's how I would lay this out

```
type Chain { ... }   // chain details (gas, name, etc)
type CoreConfig { ... }  // configuration options for the contracts to be deployed
type CoreContracts { ... } // the contracts to be deployed
type BridgeConfig { ... }  // configuration options for the contracts to be deployed
type BridgeContracts { ... } // the contracts to be deployed

class BaseDeploy { 
    readonly chain: Chain;
}

class CoreDeploy extends BaseDeploy {
    contracts: CoreContracts
    config: CoreConfig
}

class BridgeDeploy extends BaseDeploy {
    contracts: BridgeContracts
    config: BridgeConfig
}
```

2021-07-16 17:09 UTC, prestwich commented on typescript/optics-deploy/src/bridge.ts
> +  static freshFromConfig(config: ChainConfig, coreDeployPath: string): BridgeDeploy {
fancy way

```
export type Chain { ... }
export class BaseContracts { ... }
export class BaseConfig { ... }

export class BridgeConfig extends BaseConfig { ... }
export class CoreConfig extends BaseConfig { ... }
export class BridgeContracts extends BaseContracts { ... }
export class CoreContracts extends BaseContracts { ... }

export class Deploy<T extends BaseConfig, U extends BaseContracts> { 
    readonly chain: Chain
    readonly config: T
    contracts: U
}
```

2021-07-18 12:20 UTC, anna-carroll commented on solidity/optics-core/js/readDeployOutput.js
> +const fs = require('fs');
i would like to fix all of the verify-related stuff in a separate PR. there are a couple issues with it right now

2021-07-18 12:25 UTC, anna-carroll commented
made issues for outstanding work 
- verify script fixes #498 
- refactor `Deploy` class #499

2021-07-18 12:27 UTC, prestwich approved these changes

2021-07-18 12:28 UTC, merged