add: deploy and enroll new chain
celo-org/optics-monorepo pull request #514
Opened 2021-07-30 17:02 UTC by ErinHales

- [ ] add test

2021-08-02 17:13 UTC, prestwich commented on typescript/optics-deploy/src/deployOptics.ts
> +  chains.forEach(async (chain, i) => {
should this be

` await Promise.all(chains.map(async (chain, i) => { ... }));`

2021-08-09 17:53 UTC, prestwich commented on typescript/optics-deploy/src/core/index.ts
> +    await enrollRemote(newChain, chain);
hmm, will this work if the previous deploy ownership has been transferred to governance?

2021-08-11 12:30 UTC, anna-carroll requested changes
👯‍♀️

2021-08-11 12:30 UTC, anna-carroll commented on typescript/optics-deploy/src/core/index.ts
> +    await enrollRemote(newChain, chain);
no, it wont :(

2021-08-11 12:30 UTC, anna-carroll commented on typescript/optics-deploy/src/core/index.ts
> +    if (i === 0) {
```
    if (i === 0) {
      await transferGovernorship(chain, newChain);
    }

    await relinquish(newChain);
```
this should be done outside of the `chains.map`. we are attempting to `relinquish` ownership of the `newChain` N times, where N = `chains.length` - this won't work

outside of the `map` statement,
```
      Deploy governorChain = chains[0];
      await transferGovernorship(governorChain, newChain);

      await relinquish(newChain);
```

2021-08-11 12:30 UTC, anna-carroll commented on typescript/optics-deploy/src/core/index.ts
> +    await enrollRemote(newChain, chain);
in order to enroll the `newChain` in each existing `chain`, each existing chain will need the `governor` to send that transaction.

2021-08-16 22:56 UTC, prestwich commented
closing this as requiring further consideration

2021-08-16 22:56 UTC, closed without merging