feat: Request Details
celo-org/optics-monorepo pull request #536
Opened 2021-08-06 16:30 UTC by anna-carroll

closes #460

2021-08-06 16:32 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
> +        RequestDetails, // 3
Please document that after deployment all new types MUST be at the end of the list, as inserting into the list will cause messages in flight to be misinterpreted

2021-08-06 16:43 UTC, prestwich requested changes

2021-08-06 16:43 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
> +        require(isDetails(_action) || isRequestDetails(_action) || isTransfer(_action), "!action");
now that there are more than 2, we should make a `isValidActionType` function

2021-08-06 16:43 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
>      uint256 private constant TOKEN_ID_LEN = 36;
please document that length is the ONLY dsitinguishing identifier for incoming action types. Bridge messages do NOT include an explicit type tag. If we want to add any new messages in the future they MUST have distinct lengths.

2021-08-06 16:43 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
> -            _len == TOKEN_ID_LEN + DETAILS_LEN
abstract into a `isValidMessageLength` function

2021-08-06 16:43 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +    function updateDetails(address _token, uint32 _destination) public {
this is still `public`. I was thinking that we were moving to remote pull of details only. Do we still want to allow local users to push details to the other chain?

2021-08-06 16:43 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +    function _ensureToken(bytes29 _tokenId)
why has this moved files?

2021-08-06 16:43 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +    function _ensureToken(bytes29 _tokenId)
oh I see, it's because you added the `_requestDetails` 

this needs gas benchmarking to ensure that that is safe with the 500k constraint

2021-08-06 16:52 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +    function updateDetails(address _token, uint32 _destination) public {
there should still be `external` access because what if a Token changes its name?

2021-08-06 17:31 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
> +        require(isDetails(_action) || isRequestDetails(_action) || isTransfer(_action), "!action");
👍

2021-08-06 17:32 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
> -            _len == TOKEN_ID_LEN + DETAILS_LEN
👍

2021-08-06 17:32 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
>      uint256 private constant TOKEN_ID_LEN = 36;
👍

2021-08-06 17:32 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
>      uint256 private constant TOKEN_ID_LEN = 36;
or we could copy Governance and make a 1-byte identifier from the get-go?

2021-08-06 17:36 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +    function updateDetails(address _token, uint32 _destination) public {
that should be very uncommon 🤔  I think the "officially supported" thing to do there should be to have governance instruct the router to send another `requestDetails` message

2021-08-06 17:37 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
>      uint256 private constant TOKEN_ID_LEN = 36;
I would prefer to document instead of refactor at this point

2021-08-09 13:30 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +    function updateDetails(address _token, uint32 _destination) public {
well, for example, $CELO changed its name from Celo Gold 🤔 

> governance instruct the router to send another requestDetails message

this wouldn't be possible without an upgrade, but yeah - could do

2021-08-09 13:36 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
> +        require(isDetails(_action) || isRequestDetails(_action) || isTransfer(_action), "!action");
https://github.com/celo-org/optics-monorepo/pull/536/commits/1fdd3c851a7cad141584b09817f9ebea612077bc

2021-08-09 13:36 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
> -            _len == TOKEN_ID_LEN + DETAILS_LEN
https://github.com/celo-org/optics-monorepo/pull/536/commits/de54ed45667498279fc3bc63febc96e170c57f52

2021-08-09 14:21 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +    function updateDetails(address _token, uint32 _destination) public {
i don't feel too strongly - what's the downside of leaving it external?

2021-08-09 14:48 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
>      uint256 private constant TOKEN_ID_LEN = 36;
dang, i feel like this locks us into a design that's more brittle & not upgradable because of the in-flight issue.. i did a refactor for this, but I can revert it if you feel strongly it's stupid to add these changes right now https://github.com/celo-org/optics-monorepo/pull/536/commits/76d0fa3ed00ae10ecbefab340574b702895e2af0

2021-08-09 14:51 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeMessage.sol
> +        RequestDetails, // 3
https://github.com/celo-org/optics-monorepo/pull/536/commits/eb73adf0be0037546ddf9139cd502eb92a7ed21f

2021-08-09 17:50 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +    function updateDetails(address _token, uint32 _destination) public {
people can ping it a bunch and make spam messages taht are annoying to distinguish from good ones

2021-08-11 11:35 UTC, anna-carroll reviewed
I could not repro the error that the tests are failing with locally 🤔 
ran the tests locally and they're all passing

2021-08-11 16:23 UTC, prestwich commented
agree with reverting the `SafeMath` inclusion. However, please add a comment stating why overflow on multiplication is not an issue

2021-08-11 16:35 UTC, prestwich requested changes

2021-08-11 16:35 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +        bytes32 _remote = _mustHaveRemote(_destination);
This will cause a revert if we don't have a registered remote for the relevant domain

Suppose token 1000:0xabcd goes to domain 2000 and then here. If this domain doesn't have the `1000`  router registered, those tokens will be permanently locked on their home domain

Change this from `_mustHaveRemote`

```
bytes32 _remote = remotes[domain];
if (_remote == bytes32(0)) { return ; }
```

and add an appropriate comment about why it is done that way

2021-08-11 16:35 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +        bytes32 _idHash = _tokenId.keccak();
nit: newline before variable declaration here

2021-08-11 16:35 UTC, prestwich commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +        // emit event
nit: newline before comment

2021-08-11 16:35 UTC, prestwich commented on typescript/optics-tests/test/bridge/bridge.test.ts
> +const BRIDGE_MESSAGE_TYPES = {
can we move this into the optics hardhat plugin?

2021-08-11 16:35 UTC, prestwich commented on typescript/optics-tests/test/bridge/bridge.test.ts
> +    bridgeRouter =deploy.contracts.bridgeRouter!.proxy
nit: space after `=`

2021-08-11 16:35 UTC, prestwich commented on typescript/optics-tests/test/bridge/bridge.test.ts
> +    bridgeRouter =deploy.contracts.bridgeRouter!.proxy
nit: use destructuring

2021-08-11 16:44 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +        bytes32 _idHash = _tokenId.keccak();
I have ben doing no-whitespace in new contract work thus far

2021-08-11 16:44 UTC, anna-carroll commented on solidity/optics-xapps/contracts/bridge/BridgeRouter.sol
> +        // emit event
ditto above

2021-08-11 17:15 UTC, anna-carroll commented on typescript/optics-tests/test/bridge/bridge.test.ts
> +    bridgeRouter =deploy.contracts.bridgeRouter!.proxy
added space: https://github.com/celo-org/optics-monorepo/pull/536/commits/b080cc156a0604f165a7d897066a293d75e7a521

2021-08-11 17:50 UTC, prestwich commented on typescript/optics-tests/test/bridge/bridge.test.ts
> +const BRIDGE_MESSAGE_TYPES = {
gonna open an issue for this

2021-08-11 17:56 UTC, merged