start on tracing overhaul
celo-org/optics-monorepo pull request #593
Opened 2021-08-17 20:52 UTC by emberian

currently working on:

1. reducing the number of events (lots of extraneous ones?)
2. increasing the number of spans
3. making sure the relations between them make sense
4. adding fields + structured metadata connecting disparate things, esp loading up spans with all the metadata events later reference
5. instrumenting optics-base

needed before merge:
1. inspect spans+events on output at different levels to ensure message utility
2. tweak tracing levels (lots of info rn)
3. yeet span into infra

Closes #580

2021-08-17 20:54 UTC, emberian commented on rust/processor/src/processor.rs
> +                // TODO: ought this not be updated if SkipSleep?
@prestwich can you help me repair the control flow here? (i hate upgrading second class control flow to first class...). i'm overal confused about the timed loop.

2021-08-17 21:14 UTC, prestwich commented on rust/processor/src/processor.rs
> +                // TODO: ought this not be updated if SkipSleep?
Which part of the control flow do you think is broken?

The purpose of the timed loop is to 
a) walk the agent through the process of getting the next message, and ensuring it has the info necessary to process it
b) rate limit access to the chain RPC so we don't overload nodes or get API access revoked

Generally, the actions described in the comment at the top of the loop are correct and should be represented in the the internal flow. This loop is a bit of a kludge. Can we start by breaking it down into smaller pieces that represent those actions?

2021-08-18 20:43 UTC, emberian commented on rust/processor/src/processor.rs
> +    async fn try_msg_by_domain_and_seq(&self, domain: u32, current_seq: u32) -> Result<u32> {
@prestwich what do you think about this restructuring?

2021-08-18 20:45 UTC, emberian commented
@yourbuddyconner i'm almost ready to sit down and figure out spanyeet, the processor instrumentation should Make Sense now and be a good example for the pattern to push into the rest of the code

2021-08-18 21:44 UTC, prestwich commented on rust/processor/src/processor.rs
> +    async fn try_msg_by_domain_and_seq(&self, domain: u32, current_seq: u32) -> Result<u32> {
hmmm so you're making me re-examine how this was designed in the first place and I'm seeing more holes

z`Replica::next_to_process` was intended to be a hint on where in the message set the processor should start looking for unprocessed messages. However, if we retrieve it from the chain, it's possible that we end up skipping local processing of a batch of messages because some other processor has submitted a later message

e.g. 
- messages 0-50 arrive in an `Update`
- Processor A processes ONLY message 46
- `nextToProcess` is set to 47
- Processor B starts processing at 47, _regardless of whether any unprocessed messages exist in 1-45_

Proposed fix:
- Delete `nextToProcess` on Replica.sol
- `Processor` inspects _each_ message
- `Processor` persists the sequence of the last inspected message in its DB as `lastInspected`
- on agent startup, processor pulls `lastInpected` from its DB and starts processing at that number

Thoughts

2021-08-20 21:07 UTC, prestwich requested changes

2021-08-20 21:07 UTC, prestwich commented on rust/optics-ethereum/src/replica.rs
> -    #[tracing::instrument(err)]
PR needs to be marked as closing:
#619 #620 #621 

cc @anna-carroll

2021-08-20 21:07 UTC, prestwich commented on rust/optics-core/src/lib.rs
> +impl core::fmt::Display for Update {
will need a rebase as this struct has moved already in `main`. but wait until after #592 is merged

2021-08-20 21:07 UTC, prestwich commented on rust/processor/src/processor.rs
> +    /// Returns the next sequence number to try and process, for the given domain.
No longer true. Now returns a boolean indicating whether the message should be marked as inspected (i.e. whether the exterior loop should make progress or run again

2021-08-20 21:07 UTC, prestwich commented on rust/processor/src/processor.rs
> +                        sequence = next_to_inspect
maybe add domain informaiton here? `self.replica.domain()` and `self.home.domain()` ?

2021-08-20 21:07 UTC, prestwich commented on rust/processor/src/processor.rs
> +    /// Returns the next sequence number to try and process, for the given domain.
so `Ok(true)` means either "skip this message" or "this message was processed"

2021-08-20 21:07 UTC, prestwich commented on rust/processor/src/processor.rs
> +    /// Returns the next sequence number to try and process, for the given domain.
while `Ok(false)` means "try again later

2021-08-20 21:07 UTC, prestwich commented on rust/processor/src/processor.rs
> +            sleep(Duration::from_secs(self.interval)).await;
should add a comment on this behavior. Once we've established that a message exists and we have a proof, we wait here until the update containing it is confirmed on the `Replica`

2021-08-23 17:28 UTC, prestwich commented
needs rebase onto main after #629 

- solidity changes should be dropped from this PR

2021-08-24 16:35 UTC, emberian commented on rust/processor/src/processor.rs
> +            sleep(Duration::from_secs(self.interval)).await;
i think of `info!()` as an executable comment :) tweaking its prose.

2021-08-24 18:21 UTC, prestwich approved these changes

2021-08-24 18:22 UTC, merged