enhancement: disable ping-pong xApp deploy
celo-org/optics-monorepo pull request #753
Opened 2021-09-08 15:58 UTC by ErinHales

Closes #708

2021-09-08 16:01 UTC, prestwich approved these changes

2021-09-08 16:15 UTC, prestwich requested changes

2021-09-08 16:15 UTC, prestwich commented on solidity/optics-xapps/contracts/ping-pong/PingPongRouter.sol
> +        assert(true == false, "example xApp, do not deploy");
should be `require(false, "...");`

2021-09-08 19:51 UTC, ErinHales commented on solidity/optics-xapps/contracts/ping-pong/PingPongRouter.sol
> +        assert(true == false, "example xApp, do not deploy");
Oh lol, yeah. That's better 😂

2021-09-09 18:01 UTC, prestwich approved these changes

2021-09-09 18:01 UTC, merged