refactor: instantiate OpticsMessage with event instead of transaction receipt
celo-org/optics-monorepo pull request #842
Opened 2021-09-24 20:40 UTC by anna-carroll

2021-09-27 15:53 UTC, prestwich commented
Initially it was instantiated from an event. The reason I changed it to be instantiated from a receipt was to preserve blockheight, and other tx confirmation info. Does this PR preserve those?

2021-09-27 17:25 UTC, anna-carroll commented
TransactionReceipt (which is ContractReceipt without parsed Events array):
```
export interface TransactionReceipt {
    to: string;
    from: string;
    contractAddress: string,
    transactionIndex: number,
    root?: string,
    gasUsed: BigNumber,
    logsBloom: string,
    blockHash: string,
    transactionHash: string,
    logs: Array<Log>,
    blockNumber: number,
    confirmations: number,
    cumulativeGasUsed: BigNumber,
    effectiveGasPrice: BigNumber,
    byzantium: boolean,
    type: number;
    status?: number
};
```
Log (which we can swap out for Event here):
```
export interface Log {
    blockNumber: number;
    blockHash: string;
    transactionIndex: number;

    removed: boolean;

    address: string;
    data: string;

    topics: Array<string>;

    transactionHash: string;
    logIndex: number;
}
```

diff (which we can get by querying the transaction if we want)
```
    to: string;
    from: string;
    transactionIndex: number,
    root?: string,
    gasUsed: BigNumber,
    logsBloom: string,
    confirmations: number,
    cumulativeGasUsed: BigNumber,
    effectiveGasPrice: BigNumber,
    byzantium: boolean,
    type: number;
    status?: number
```

2021-09-27 17:39 UTC, anna-carroll commented
you know what, i will just pass in the event and the contract receipt

2021-09-27 20:18 UTC, prestwich commented on typescript/optics-provider/src/provider.ts
> +  async getTransactionReceipt(nameOrDomain: string | number, transactionHash: string): Promise<TransactionReceipt> {
design question: how many standard provider methods should we be wrapping and re-surfacing, as opposed to making the use fetch the provider?


e.g. what is preferred

```
// more boilerplate, less verbose for user
multi.getTransactionReceipt('ethereum', '0x...')

/// OR 

// less boilerplate for us, more verbose for user
multi.mustGetProvider('etheruem').getTransactionReceipt('0x...')
```

2021-09-27 23:16 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +interface RichEvent {
TODO: i wanted to think of some kind of interface that would include all of the information we want for an event which would be returned to a frontend - particularly: 
1. which chain it happened on (so FE can link to block explorer)
2. timestamp (for nice UI things) 
3. transaction hash (again for link to block explorer)

this PR doesn't actually implement all of these things yet. 
need to think about it more in the morning.

2021-09-27 23:16 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +    status: string;
TODO: make an `enum` for this

2021-09-27 23:27 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +    const update = await this.replicaUpdateEvent();
thought: perhaps we store the event to a field on the class when we query it, and only query it if the field on the class is currently null, so we only query the event once per `OpticsMessage` instance

2021-09-28 00:42 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +import {core} from "@optics-xyz/ts-interface";
nit: combine the two imports from `ts-interface`

2021-09-28 00:43 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +export class MultiEvents {
why is this a class? seems to have no state worth speaking of

2021-09-28 00:50 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +    this.messageHash = event.args.messageHash;
can we do these as `get` functions?

2021-09-28 11:54 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/BridgeMessage.ts
> +    return opticsMessages.map(opticsMessage => BridgeMessage.fromOpticsMessage(opticsMessage, context));
> This will error if any message in the tx is not a bridge message, no?

yes you're right. we should return the successfully parsed bridge messages. it seems like perhaps not necessary to do `Promise.allSettled` given that it's synchronous to parse an `OpticsMessage` into a `BridgeMessage`? could do a try/catch or something similar to OpticsMessage.fromReceipt:
```
    let messages: OpticsMessage[] = [];
    for (const log of receipt.logs) {
      const event = MultiEvents.tryDispatchEvent(log);
      if (event) {
        const message = new OpticsMessage(event, receipt, context);
        messages.push(message);
      }
    }
    return messages;
```
^^ would be nice to be able to do this type of functionality in less or cleaner lines of code.. basically `map` but with a try/catch and discarding errors

2021-09-28 11:58 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  constructor(event: DispatchEvent, receipt: TransactionReceipt, context: OpticsContext) {
yeah, i agree, it seems ugly to me. the point of passing both is that it specifies **which event** to use, because ofc the `receipt` has an array of potentially multiple. another way to do this would be to pass the `receipt` and the `logIndex` of the event in question, but it seemed to me like this would make for weirder code instantiating the class.

the goal is: we want to instantiate the class for a single, specific event - keeping in mind that there may be multiple in one transaction or block; but we also want to preserve all of the context included in the transaction & block

the (ugly) solution i came up with (in an admittedly quick manner) was to pass both specific & general

2021-09-28 11:58 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +    this.messageHash = event.args.messageHash;
sure :~)

2021-09-28 12:08 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +import {core} from "@optics-xyz/ts-interface";
i don't think you can import them both from the same path because `TypedEventFilter` is not exported from the `index.ts` file

2021-09-28 12:19 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +export class MultiEvents {
yeah.. it doesn't :/ i think maybe i got annoyed with passing `context` into every function... but these should probably just be functions

2021-09-28 13:19 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/BridgeMessage.ts
> +    return opticsMessages.map(opticsMessage => BridgeMessage.fromOpticsMessage(opticsMessage, context));
https://github.com/celo-org/optics-monorepo/pull/842/commits/e28fea8b777fdf84b0c9f49183c6a749c0d13f82

2021-09-28 13:21 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +export class MultiEvents {
https://github.com/celo-org/optics-monorepo/pull/842/commits/f7d89158a0f91cc53712b890b4256739cbb2145a

2021-09-28 13:21 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +    status: string;
https://github.com/celo-org/optics-monorepo/pull/842/commits/d5e3cae00daf9c0805e8af61e4b7284586fe82dc

2021-09-28 13:22 UTC, anna-carroll commented on typescript/optics-provider/src/optics/examples/sendCoins.ts
> +import { mainnet } from '../index';
https://github.com/celo-org/optics-monorepo/pull/842/commits/2955f6d1596750aa8244d1a686fb4c86c44e6676

2021-09-28 14:07 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +    const update = await this.replicaUpdateEvent();
https://github.com/celo-org/optics-monorepo/pull/842/commits/b324d9ba7f3a38d7723acbdf82139a3b47de9f6c
hmmmm this is basically a shitty version of cacheing.. and significantly less readable.. wdyt @prestwich

2021-09-28 14:17 UTC, ErinHales commented
Going to look over this first thing after I get some coffee, but wanted to say thanks for stepping in here. Absolutely incredible 🌸

2021-09-28 14:46 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +interface RichEvent {
okay here's what I came up with: https://github.com/celo-org/optics-monorepo/pull/842/commits/f3c973ac1a7a8894d36406d99b9e32f310337c0c

2021-09-28 14:49 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +export async function eventToRichEvent(context: OpticsContext, nameOrDomain: string | number, event: Event): Promise<RichEvent> {
note: this costs 2 extra RPC calls per event. will be expensive / slow for big arrays of events. 

need to do two calls because `timestamp` is not included on `TransactionReceipt`

2021-09-28 14:52 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +interface RichEvent {
https://github.com/celo-org/optics-monorepo/pull/842/commits/25129882e7dad895b2255d763f369b9efe78f943

2021-09-28 15:09 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +import {core} from "@optics-xyz/ts-interface";
ugh fair. I guess file an issue to get the `dist` out of our import path at least 🤔

2021-09-28 15:12 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  constructor(event: DispatchEvent, receipt: TransactionReceipt, context: OpticsContext) {
I also appreciate doing it _right_ the first time. This is a fine kludge, but maybe in the future we change to passing the index in the receipt's log array?

2021-09-28 15:13 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +    this.messageHash = event.args.messageHash;
seems reasonable. computing them eagerly in the constructor will also catch any parsing errors

2021-09-28 15:16 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +    const update = await this.replicaUpdateEvent();
I think in the future we should consider a log-caching layer on the multi-provider. but lets omit this logic for now.

2021-09-28 15:21 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +        ...receipt,
nit, inconsistent whitespace here

2021-09-28 15:22 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +        ...receipt,
The question above about `RichReceipt` is basically "why are we erasing info here by dumpint the receipt into the rich event instead of just attaching the receipt to the rich event?

2021-09-28 15:23 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +const POLYGON_MAX_BLOCKS = 2500;
should be `1999`?

2021-09-28 15:23 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +const POLYGON_IDENTIFIERS = ["polygon", "matic", 1886350457];
module-level consts should be at top of file

2021-09-28 15:24 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +export async function getRichEvents(context: OpticsContext, nameOrDomain: string | number, contract: BaseContract, logFilter: TypedEventFilter<any, any>, startBlock?: number, endBlock?: number): Prom
should these be module-level functions, seems like they ought to be methods on the `MultiProvider` or `OpticsContext`?

2021-09-28 15:28 UTC, prestwich commented on typescript/optics-provider/src/optics/events.ts
> +export async function getPolygonEvents(context: OpticsContext, nameOrDomain: string | number, contract: BaseContract, logFilter: TypedEventFilter<any, any>, startBlock?: number, endBlock?: number): P
proposed _additional_ kludge:
allow user to specify an early exit after finding a single event. E.g.  a `singleton: bool = false` argument. this allows us to prevent crawling the entire range if we're looking for a particular event

2021-09-28 15:29 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  Processed = 3
inconsistent enum declaration. either use explicit `=` on all elements of both enums or on just the first element of both

2021-09-28 15:31 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  protected storedHomeUpdateEvent: UpdateEvent | undefined;
I want to drop this caching but, in the future, use a `type EventCache = { ... } ` for things like this

2021-09-28 15:31 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  protected storedHomeUpdateEvent: UpdateEvent | undefined;
`protected cache = { ... }`

2021-09-28 15:32 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  protected storedHomeUpdateEvent: UpdateEvent | undefined;
that way it's fewer lines of declaration (more legible) and you don't have to make wordy variable names to indicate intent

2021-09-28 15:33 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  async homeUpdateEvent(): Promise<UpdateEvent | undefined> {
need to note in docs that this function may produce false positives, if the updater has signed an update on the committedRoot that does not include this message. these should be uncommon in practice. The only way to know _for sure_ is to keep an indexed set of updates and leaves :(

2021-09-28 15:37 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  async homeUpdateEvent(): Promise<UpdateEvent | undefined> {
are these `_____UpdateEvent` methods intended to be public API? I think not, right? if not, consider making them private.

Also, not a fan of the naming. no need to name it `____Event` when we return an event. the type signature makes that clear. What about `homeUpdate`

2021-09-28 18:42 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +export async function eventToRichEvent(context: OpticsContext, nameOrDomain: string | number, event: Event): Promise<RichEvent> {
nevermind, we can't have nice things - `timestamp` not available on `TransactionReceipt` actually, and `getBlock` throws for Celo

2021-09-28 18:45 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events.ts
> +export async function eventToRichEvent(context: OpticsContext, nameOrDomain: string | number, event: Event): Promise<RichEvent> {
https://github.com/celo-org/optics-monorepo/issues/848

2021-09-28 18:49 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  async homeUpdateEvent(): Promise<UpdateEvent | undefined> {
I had this initially, the thing is, that makes one of the functions `process() `which is confusing naming IMO, sounds like it's doing something on-chain

2021-09-28 21:46 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  constructor(event: DispatchEvent, receipt: TransactionReceipt, context: OpticsContext) {
resolved in latest with introduction of `Annotated<T>`

2021-09-29 02:26 UTC, prestwich commented
@anna-carroll please put me out of my misery and/or review this PR

2021-09-29 02:27 UTC, prestwich commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  async homeUpdateEvent(): Promise<UpdateEvent | undefined> {
I settled on `get____` without event. it's a little unclear for process but seems fine. 

Are they intended to be public api tho?

2021-09-29 16:00 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  async homeUpdateEvent(): Promise<UpdateEvent | undefined> {
ah shoot, you are right.

2021-09-29 16:01 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  async homeUpdateEvent(): Promise<UpdateEvent | undefined> {
i think it's good for them to be public API, if someone wants to query for just one

2021-09-29 17:02 UTC, yourbuddyconner requested changes
I want to use this. 

Please add .env to .gitignore.

2021-09-29 17:07 UTC, prestwich commented
-_-

2021-09-29 17:32 UTC, merged

2021-09-29 18:27 UTC, anna-carroll commented on typescript/optics-provider/src/optics/messages/OpticsMessage.ts
> +  async homeUpdateEvent(): Promise<UpdateEvent | undefined> {
ugh.

2021-09-30 12:53 UTC, anna-carroll reviewed
looking beautiful 😭  thank you @prestwich

2021-09-30 12:53 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events/fetch.ts
> +    event,
i wonder if it wouldn't be beneficial to have the `annotatedEvent` have all the same fields as a regular event (e.g. do `...event` here) so that people can interact with it as if its a normal event (with a few extra fields)

2021-09-30 12:53 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events/fetch.ts
> +  const callArgs = [];
this loop isn't used. i'll open a PR

2021-09-30 12:55 UTC, anna-carroll commented on typescript/optics-provider/src/optics/events/fetch.ts
> +  const callArgs = [];
https://github.com/celo-org/optics-monorepo/pull/858