fix: fix processor index/nonce conflation and add per-replica nonce storage
celo-org/optics-monorepo pull request #850
Opened 2021-09-28 20:40 UTC by ltchang2019

- bug: multiple `Replica` processors were sharing the same key for storing their latest inspected nonces
- changes:
  -  key latest nonces by replica domain
  - improve docs for pub db store functions
  - add separate prometheus `IntGaugeVec` for each `Replica` processor

2021-09-28 20:43 UTC, ltchang2019 commented on rust/agents/processor/src/processor.rs
> +                &["home", "agent"],
I only understand these prometheus objects at a very surface level but this `IntGaugeVec` doesn't look like it's getting used anywhere. @prestwich did we just forget to actually track/update this one?

2021-09-28 20:47 UTC, ltchang2019 commented on rust/optics-core/src/db/home_db.rs
>          self.store_keyed_encodable(PROOF, &leaf_index, proof)
I'm confused, are these _all caps_ prefixes supposed to describe the key or the value? It looks like most cases describe the key but its inconsistent everywhere... should consolidate to standard

2021-09-28 21:02 UTC, emberian submitted a review, later dismissed

2021-09-29 15:57 UTC, prestwich commented on rust/agents/processor/src/processor.rs
> +                &["home", "agent"],
so the `&[&str]` here is identifiers for groups of "labels" on the data. It should probably be `&["home", "replica", "agent"]` for this group of metrics. and then when we make a specific metric

Each metric is updated on L78 in the processor 

```
                self.next_nonce
                    .with_label_values(&[self.replica.name(), AGENT_NAME])
                    .set(next_nonce as i64);
```

2021-09-29 15:58 UTC, prestwich commented on rust/optics-core/src/db/home_db.rs
>          self.store_keyed_encodable(PROOF, &leaf_index, proof)
I think they should describe the value. Feel free to change to make consistent

2021-09-29 15:58 UTC, prestwich commented on rust/agents/processor/src/processor.rs
> +                &["home", "agent"],
if updating the label array, also update the `with_label_values` invocation

2021-09-29 16:05 UTC, prestwich commented on rust/agents/processor/src/processor.rs
> +                .new_int_gauge(
instead of making a new one, put the one on the `Processor` into an arc (and rename it appropriately), and give the arc to each replica processor struct. then have each replica processor set given its labels.

So no metric for `next_message_index` and a shared `Arc<IntGaugeVec>` for `next_nonce`

2021-09-29 16:08 UTC, prestwich commented on rust/optics-core/src/db/typed_db.rs
> +        full_prefix.extend("_".as_bytes());
this will cause a complete DB resync right? cc @yourbuddyconner

2021-09-29 16:09 UTC, ltchang2019 commented on rust/optics-core/src/db/typed_db.rs
> +        full_prefix.extend("_".as_bytes());
Yes this will require us to scrap the existing db

2021-09-29 16:24 UTC, prestwich requested changes
metrics update

2021-09-29 16:56 UTC, ltchang2019 commented on rust/optics-core/src/db/typed_db.rs
> +        full_prefix.extend("_".as_bytes());
Either way the key prefix changes will make us do this

2021-09-29 17:00 UTC, prestwich commented on rust/optics-core/src/db/typed_db.rs
> +        full_prefix.extend("_".as_bytes());
yeah, just need to give conner a headsup when we do this. it's still relatively cheap, so no real downside but better to know than not know

2021-09-29 18:18 UTC, prestwich approved these changes

2021-09-29 18:23 UTC, merged