refactor: split up contract indexers and separate db/contract logic
celo-org/optics-monorepo pull request #925
Opened 2021-11-02 17:27 UTC by ltchang2019

2021-11-03 17:27 UTC, prestwich commented on rust/config/development/watcher-partial.json
> +    "kovanbridgerouter": {
`camelCase` for json?

2021-11-03 17:29 UTC, prestwich commented on rust/optics-core/src/traits/mod.rs
> +pub trait CommonEvents: Common + Send + Sync + std::fmt::Debug {
can you provide rationale for splitting the trait?

2021-11-03 17:35 UTC, prestwich commented on rust/optics-base/src/home.rs
> +    pub fn home(&self) -> Arc<Homes> {
We should consider moving the `Homes` arc internally, so that Homes is always clonable. the same pattern we did with OpticsDB

2021-11-03 17:39 UTC, prestwich requested changes
Okay the main thing I think this needs is documentation of the layout of all these types. How do all the traits relate to eachother and why?

2021-11-03 19:20 UTC, ltchang2019 commented on rust/optics-core/src/traits/mod.rs
> +pub trait CommonEvents: Common + Send + Sync + std::fmt::Debug {
Wasn't strictly necessary but thinking to split because `Homes` switches on chain specific contract calls while retrieval of event data is chain agnostic (just db fetches). Other alternative was to scrap `Homes` entirely and to just put all methods (contract calls and event data fetches) in `CachingHome` and have `CachingHome` implement `Home` with both contract calls and event data fetches.

2021-11-04 01:36 UTC, ltchang2019 commented
Documentation:
- Indexer traits: https://github.com/celo-org/optics-monorepo/pull/925/files#diff-6bd64866866ea21992b5ba0925c8dcaa2efca43e5d5409d369e4bec27f85be4bR1-R8
- ContractSync struct: https://github.com/celo-org/optics-monorepo/pull/925/files#diff-8915f2b78fa646fab4b83ec99793b39e5c908ed3cb74af8dc49f403ea5d40b94R16-R20
- HomeEvents/CommonEvents: `Homes` and `Replicas` abstractions, which switches over chain-specific contract methods are retained and implement `Home` and Replicas`. `CachingHome` and `CachingReplica` also provide event data (updates, messages) and thus implement `HomeEvents` and `CommonEvents`

2021-11-04 14:44 UTC, prestwich approved these changes
approved, but needs to run in dev before deployment

2021-11-04 15:18 UTC, merged